env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.20.1/geckodriver-v0.20.1-linux64.tar.gz
  - mkdir /tmp/geckodriver
  - tar -xzf geckodriver-v0.20.1-linux64.tar.gz -C /tmp/geckodriver
  - export PATH=$PATH:/tmp/gecko-driver
  - sleep 5
script: mvn install && sleep 5
